Small screan navbar
WTMSaudi/website pull request #2
Opened 2021-12-14 17:47 UTC by renad001

2021-12-14 18:17 UTC, pr-Mais requested changes

2021-12-14 18:17 UTC, pr-Mais commented on components/layout/navbar.tsx
> +const NavbarItem = ({ label, herf }: NavbarItemProps) => {
```suggestion
const NavbarItem = ({ label, href }: NavbarItemProps) => {
```

2021-12-14 18:18 UTC, pr-Mais commented
Can you please provide a sufficient description + screenshots to the changes you're suggesting?

2021-12-15 04:46 UTC, renad001 commented
only add a link to blog page
 
![blog link](https://user-images.githubusercontent.com/32821521/146124676-80c9dcc4-ddd0-48a7-af37-58f6e215bac6.gif)


reorganize the navbar 
![en nav](https://user-images.githubusercontent.com/32821521/146124751-8d76edde-41b1-4a82-9265-557a9730838a.gif)
![ar nav](https://user-images.githubusercontent.com/32821521/146124757-cb56bb9b-8582-4648-94ae-d0baf1d33c82.gif)

2022-01-04 19:28 UTC, merged